# Workspace definition
workspace:
  base: /test
  path: nexteuropa_varnish

# Services needed for the build
services:
  mysql:
    image: fpfis/mysql56
  web:
    image: fpfis/php56-dev
    environment:
     - DOCUMENT_ROOT=/test/nexteuropa_varnish/build
  varnish:
    image: fpfis/varnish-d7:latest
    environment:
      - BACKEND_HOST=web
      - BACKEND_PORT=8080
      - VCL_DIR=/test/nexteuropa_varnish/vcls

pipeline:
  test-varnish:
    image: fpfis/php56-dev
    commands:
      - sleep 5
      - curl -v varnish
